# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18220683f11b9a6c912e469112cac08145c980de70295cd15e47c2b5581f175e5eaec0e64e373a28b80dfc31395223bb5a77b8e3a1d61b8ae6275dc3fa0f368d

test:
  secret_key_base: 43110f76e662dff7830c863ee379883439ccf0c5bce5d00f5018a0cffb93d51a3d6307e6fb24d6ae0093792c0e301c359dd8bbea10329ef0aadb1f7e622aea2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
